# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  joss_build:
    docker:
      - image: circleci/python:3.6.2-jessie-browsers
    resource_class: small
    environment: 
      - JOSSROOT:  JOSS_paper
      - J_PAPERROOT: SyntenyViz_paper
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
            key: depsJOSS-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run: |
            echo "export PATH=${HOME}/${CIRCLE_WORKING_DIRECTORY}/${JOSSROOT}/.scripts:${PATH}" >> ${BASH_ENV}
            source ${BASH_ENV}
      - run: |
            ls -aRl 
            echo $HOME
            pwd
      - run: |
            cd "${HOME}/${CIRCLE_WORKING_DIRECTORY}/${JOSSROOT}/${J_PAPERROOT}"
            compile "${JOSSNAME}/paper.md"
      - save_cache:
            key: depsJOSS-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            paths: 
              - ".venv"
              - "/usr/local/bin"
              - "/usr/local/lib/python3.6/site-packages"
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: $JOSSPATH
          destination: JOSS_PDF

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  build:
    jobs:
      - joss_build
