# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  joss_build:
    docker:
      - image: circleci/python:3.6.9-stretch
    resource_class: small
    environment:
      - JOSSROOT:  JOSS_paper
      - J_PAPERROOT: SyntenyViz_paper
      - CONDA_BIN_ROOT: .miniconda/miniconda3/bin
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
            key: depsJOSS-{{ .Branch }}-{{ checksum "JOSS_paper/.scripts/compile" }}
      - run: |
            pip install --upgrade pip
            sudo apt-get update -y
            sudo apt-get install -y pandoc-citeproc
            sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-generic-recommended

            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
            bash ~/miniconda.sh -p ${HOME}/.miniconda -b
            source ${HOME}/.miniconda/bin/activate
            conda init -q
            echo "export PATH=${HOME}/${CONDAROOT_BIN_ROOT}:${PATH}" >> ${BASH_ENV}

            tlmgr init-usertree
            tlmgr install tools
            tlmgr update --self --all
            tlmgr install marginnote xcolor etoolbox titlesec hyperref caption tcolorbox amsmath iftex
            tlmgr install biblatex logreq seqsplit xstring float
            conda install -c conda-forge texlive-core -y
            conda install -c conda-forge/label/cf201901 pandoc -y

            echo "export PATH=${HOME}/project/${JOSSROOT}/.scripts:${PATH}" >> ${BASH_ENV}
            source ${BASH_ENV}

            cd "${HOME}/project/${JOSSROOT}/${J_PAPERROOT}"
            compile paper.md
      - save_cache:
            key: depsJOSS-{{ .Branch }}-{{ checksum "JOSS_paper/.scripts/compile" }}
            paths:
              - "/usr/local/bin"
              - "/usr/local/lib/python3.6/site-packages"
              - "home/circleci/.miniconda"
              - "home/circleci/texmf"
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
            path: JOSS_paper
            destination: JOSS_PDF
  cloc_account: 
    docker:
      - image: circleci/python:3.6.9-stretch
    resource_class: small
    environment:
      - GIT_URL: https://github.com/DPP4ResearchGroup/SyntenyViz.git
      - GIT_ROOT: SyntenyViz
    steps:
      - checkout
      - run: |
           git clone ${GIT_URL}
           sudo apt-get install cloc -y
           ls -aRl
           cd "${GIT_ROOT}"
           ls -aRl
           pwd
           export lastLog=$(git log --format="%H" -n 1)
           echo $lastLog
           cloc $lastLog > cloc_log.log
      - store_artifacts:
           path: SyntenyViz
           destination: Syn_Log
# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  build:
    jobs:
    #  - joss_build
      - cloc_account
